name: AUX Package

on:
    push:
        branches:
            - main

jobs:
    aux-on-latest-release:
        runs-on: ubuntu-latest
        env:
            GITHUB_TOKEN: ${{ github.token}}
        
        steps:
            - name: Checkout Source
              uses: actions/checkout@v3
  
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: 20
                registry-url: https://npm.pkg.github.com/
                scope: '@mnicholstamu'
